config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :albums do
  	resources :images
  end

  resources :groups
  
  resources :users, only: [] do
  	get :dashboard
  end
  
  root 'home#site_index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
	belongs_to :user
	has_many :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_users
  has_many :group_userships, class_name: 'User', through: :group_users

  accepts_nested_attributes_for :group_users

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group, optional: true
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :album

	has_attached_file :album_image,
    storage: :s3,
    s3_credentials: {
      access_key_id: ENV["aws_access_key_id"],
      secret_access_key: ENV["aws_secret_access_key"],
      bucket: "image-album-#{Rails.env}"
    },
    s3_region: "ap-south-1",
    path: "image/:attachment/:id/:style/:filename",
    url: ":s3_domain_url",
		styles: { 
      small: "100x100#",
      medium: "220x220#"
     },
		default_url: "400x400.png"

  validates_attachment_content_type :album_image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :albums
  has_many :groups
  has_many :group_users
  has_many :group_userships, class_name: "Group", through: :group_users
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController


	def index
		@album = current_user.albums.all
	end

	def show
		@album = Album.find(params[:id])
		@images = @album.images
	end

	def new
		@album = current_user.albums.new
	end

	def create
		@album = current_user.albums.create(album_params)

		respond_to do |format|
			if @album.save 
    			format.html { redirect_to @album, notice: 'Album successfully created!' }
				format.json { render :show, status: :created, location: @album }
			else
				format.html { render :new }
				format.json { render json: @album.errors, status: :unprocessable_entity}\
			end
		end

	end

	private
		def album_params
			params.require(:album).permit(:title, :user_id)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

	def new
		@group = current_user.groups.new
		1.times { @group.group_users.build}
	end

	def create
		@group = current_user.groups.create(group_params)
		respond_to do |format|
			if @group.save 
    			format.html { redirect_to @group, notice: 'Group successfully created' }
				format.json { render :show, status: :created, location: @group }
			else
				format.html { render :new }
				format.json { render json: @group.errors, status: :unprocessable_entity}\
			end
		end
	end

	def show
		@group = Group.find(params[:id])
	end

	private

	def group_params
		params.require(:group).permit(:name, :user_id,
		group_users_attributes: [:user_id, :group_id]
	)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def site_index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	before_action :set_album
	before_action :set_image, only: [:show, :edit, :update, :destroy]

	def index
		@images = @album.images.all
	end
	
	def new
		@image = @album.images.new
	end

	def create
		@image = @album.images.create(image_params)

		respond_to do |format|
			if @image.save
				format.html {redirect_to album_path(@album), notice: "Image uploaded successfully!"}
				format.json {render :show, status: :created, location: @album }
			else
				format.html {render :new}
				format.json {render json: @image.errors, status: :unprocessable_entity}
			end
		end
	end

	private

	def set_album
		@album = Album.find(params[:album_id])
	end

	def set_image
		@image = Image.find(params[:id])
	end

	def image_params
		params.require(:image).permit( :album_id, :title, :date_taken, :album_image)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def dashboard
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/index.html.erb
<div>
	<% @album.each do |album| %>
		<%= album.title %>
		<%= link_to "View Album", album_path(album) %>
	<% end %>
</div>
	

app/views/albums/new.html.erb
<h2>Create a New Album</h2>

<div> 
	<% if @album.errors.any? %>
		<div id="error_explanation">
  			<h2>Error!  See below for errors!</h2>
  			<ul>
  				<% @album.errors.full_messages.each do |message| %>
    				<li><%= message %></li>
  				<% end %>
  			</ul>
		</div>
    <% end %>

	<%= form_for @album do |f| %>
		<%= f.text_field :title %>
		<%= f.submit "Create Album" %>
	<% end %>
</div>

app/views/albums/show.html.erb
<h1> <%= @album.title %> </h1>

<p> <%= link_to "Add Image", new_album_image_path(@album) %> </p>

<div>
	<% @images.each do |image| %>
		<p> <%= image.title %> </p>
		<p> <%= image.date_taken %> </p>
		<%= image_tag(image.album_image(:medium)) %>
	<% end %>
</div>

app/views/groups/_group_user_fields.html.erb
<div>
	<%= f.collection_select( :user_id, User.all, :id, :first_name )  %>
</div>

app/views/groups/new.html.erb
<h2> Create a New Group! </h2>


<div> 
	<% if @group.errors.any? %>
		<div id="error_explanation">
  			<h2>Error!  See below for errors!</h2>
  			<ul>
  				<% @group.errors.full_messages.each do |message| %>
    				<li><%= message %></li>
  				<% end %>
  			</ul>
		</div>
    <% end %>

	<%= form_for @group do |f| %>
	<div>
	 <%= f.label :name %>
	 <%= f.text_field :name %>
	</div>

	<div>
		<%= f.fields_for :group_users do |group_users|%>
			<%= render 'group_user_fields', f: group_users %>
		<% end %>
		<div class = "add-more-group-users" >
			<%= link_to_add_association 'Add another Group user', f, :group_users %>
		</div>
	</div>
		<%= f.submit "Create Group" %>
	<% end %>
</div>

app/views/groups/show.html.erb
<h2>Group successfully created</h2>
<h1> <%= @group.name %> </h1>

app/views/home/site_index.html.erb
<h1>Welcome to the Photo App</h1>

app/views/images/new.html.erb
<div>
	<% if @image.errors.any? %>
		<div id="error_explanation">
  			<h2>Error!  See below for errors!</h2>
  			<ul>
  				<% @image.errors.full_messages.each do |message| %>
    				<li><%= message %></li>
  				<% end %>
  			</ul>
		</div>
    <% end %>

	<%= form_for [@album, @image], html: { multipart: true } do |f| %>
		<%= f.file_field :album_image %>
		<%= f.text_field :title %>
		<%= f.text_field :date_taken %>
		<%= f.submit "Add Image" %>
	<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if !(user_signed_in?) %>
      <p> <%= link_to("Share photos now!", new_user_registration_path) %> </p>
      <p> <%= link_to("Sign in", new_user_session_path) %> </p>
    <% else %>
      <p> <%= link_to("Log out", destroy_user_session_path, method: :delete) %> </p>
      <p> <%= link_to("Dashboard", user_dashboard_path(current_user)) %> </p>
      <p> <%= link_to("Edit account", edit_user_registration_path) %> </p>
    <% end %>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/users/dashboard.html.erb
<h1> My Dashboard </h1>

<p> <%= link_to("Create New Album", new_album_path) %> </p>
<p> <%= link_to("View Albums", albums_path) %> </p>

<p> <%= link_to("Create New Group", new_group_path) %> </p>